# Generated by Django 3.2 on 2022-02-04 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_user',
        ),
    ]
